// <auto-generated />
using AllowedPartnerV2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AllowedPartnerV2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250623225147_InitWithOneToMany")]
    partial class InitWithOneToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllowedPartnerV2.Model.Items", b =>
                {
                    b.Property<string>("partneritemref")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partnerkey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<long>("unitprice")
                        .HasColumnType("bigint");

                    b.HasKey("partneritemref");

                    b.HasIndex("partnerkey");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AllowedPartnerV2.Model.Partner", b =>
                {
                    b.Property<string>("partnerkey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("partnerpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partnerrefno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("totalamount")
                        .HasColumnType("bigint");

                    b.HasKey("partnerkey");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("AllowedPartnerV2.Model.Items", b =>
                {
                    b.HasOne("AllowedPartnerV2.Model.Partner", "Partner")
                        .WithMany("Items")
                        .HasForeignKey("partnerkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("AllowedPartnerV2.Model.Partner", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
